# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CreateRole.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CreateRole.proto',
  package='',
  serialized_pb='\n\x10\x43reateRole.proto\"5\n\rCreateRoleReq\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x12\n\nprofession\x18\x02 \x02(\t\"4\n\rCreateRoleRes\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x13\n\x0b\x63haracterId\x18\x02 \x01(\t')




_CREATEROLEREQ = _descriptor.Descriptor(
  name='CreateRoleReq',
  full_name='CreateRoleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='CreateRoleReq.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='profession', full_name='CreateRoleReq.profession', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=73,
)


_CREATEROLERES = _descriptor.Descriptor(
  name='CreateRoleRes',
  full_name='CreateRoleRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CreateRoleRes.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='characterId', full_name='CreateRoleRes.characterId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=75,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['CreateRoleReq'] = _CREATEROLEREQ
DESCRIPTOR.message_types_by_name['CreateRoleRes'] = _CREATEROLERES

class CreateRoleReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEROLEREQ

  # @@protoc_insertion_point(class_scope:CreateRoleReq)

class CreateRoleRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEROLERES

  # @@protoc_insertion_point(class_scope:CreateRoleRes)


# @@protoc_insertion_point(module_scope)
